name: Website Monitoring

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  monitor_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install axios nodemailer
      
      - name: Run website check
        id: website_check
        run: node website-monitor.js
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          EXPECTED_STATUS: ${{ secrets.EXPECTED_STATUS || '200' }}
          MAX_RESPONSE_TIME: ${{ secrets.MAX_RESPONSE_TIME || '5000' }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE || 'gmail' }}
      
      - name: Read status results
        id: read_status
        if: always()
        run: |
          if [ -f status.json ]; then
            STATUS=$(cat status.json | jq -r '.status')
            RESPONSE_TIME=$(cat status.json | jq -r '.responseTime')
            echo "status=$STATUS" >> $GITHUB_OUTPUT
            echo "response_time=$RESPONSE_TIME" >> $GITHUB_OUTPUT
          else
            echo "status=UNKNOWN" >> $GITHUB_OUTPUT
            echo "response_time=0" >> $GITHUB_OUTPUT
          fi
          
      - name: Update status history
        if: always()
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          date +"%Y-%m-%d %H:%M:%S" >> status_history.log
          echo "Status: ${{ steps.read_status.outputs.status }}" >> status_history.log
          echo "Response Time: ${{ steps.read_status.outputs.response_time }} ms" >> status_history.log
          echo "---" >> status_history.log
          git add status_history.log
          git commit -m "Update status log" || echo "No changes to commit"
          git push || echo "Nothing to push"
